# Generated by Django 4.2.7 on 2024-12-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuanLyTaiLieuHocTap',
            fields=[
                ('idLopHoc', models.IntegerField(db_column='IDLopHoc')),
                ('idTaiLieu', models.IntegerField(db_column='IDTaiLieu', primary_key=True, serialize=False)),
                ('tenTaiLieu', models.CharField(db_column='TenTaiLieu', max_length=200)),
                ('description', models.CharField(db_column='Descriptions', max_length=800, null=True)),
                ('loaiTaiLieu', models.CharField(db_column='LoaiTaiLieu', max_length=100)),
                ('link', models.CharField(db_column='Link', max_length=255)),
            ],
        ),
    ]
