# Generated by Django 4.2.7 on 2024-12-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ducapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quanlytailieuhoctap',
            name='link',
            field=models.CharField(db_column='Links', max_length=255),
        ),
    ]
