# Generated by Django 4.2.7 on 2024-12-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ducapp', '0002_alter_quanlytailieuhoctap_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quanlytailieuhoctap',
            name='link',
            field=models.CharField(db_column='Link', max_length=255),
        ),
    ]
